# run_all.py
# -*- coding: utf-8 -*-
"""
Unified training and testing for all baseline models on preprocessed HPO-CLD data.

Loads features from prepared_data/features.npz (generated by prepare_data.py),
trains each model, evaluates on test set, and saves a comparison summary.

Supported models: KNN, LogisticRegression, GaussianNB, RandomForest, TFN

Usage:
  # Step 1: Preprocess data (only once)
  python comparison/prepare_data.py --root HPO-CLD --outdir prepared_data

  # Step 2: Train & test all models
  python comparison/run_all.py --data_dir prepared_data

  # Or train specific models only
  python comparison/run_all.py --data_dir prepared_data --models KNN RandomForest

  # Train TFN with more epochs
  python comparison/run_all.py --data_dir prepared_data --models TFN --tfn_epochs 100
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np

_PROJECT_ROOT = Path(__file__).resolve().parent.parent


def load_prepared_data(data_dir: Path):
    """Load preprocessed features from npz."""
    npz = np.load(data_dir / "features.npz", allow_pickle=True)
    X = npz["X"].astype(np.float32)
    y = npz["y"].astype(np.int64)
    is_train = npz["is_train"].astype(bool)
    is_test = npz["is_test"].astype(bool)
    return X, y, is_train, is_test


def evaluate_metrics(y_true: np.ndarray, y_pred: np.ndarray,
                     y_proba: Optional[np.ndarray] = None) -> Dict[str, float]:
    from sklearn.metrics import accuracy_score, recall_score, f1_score, roc_auc_score
    if y_true.size == 0:
        return {"acc": 0.0, "recall_macro": 0.0, "f1_macro": 0.0, "auc_ovr_macro": 0.0}
    out = {
        "acc": float(accuracy_score(y_true, y_pred)),
        "recall_macro": float(recall_score(y_true, y_pred, average="macro", zero_division=0)),
        "f1_macro": float(f1_score(y_true, y_pred, average="macro", zero_division=0)),
    }
    auc = 0.0
    if y_proba is not None and y_proba.ndim == 2 and len(np.unique(y_true)) > 1:
        try:
            auc = float(roc_auc_score(y_true, y_proba, multi_class="ovr", average="macro"))
        except Exception:
            pass
    out["auc_ovr_macro"] = auc
    return out


# =============================================
# Sklearn baselines
# =============================================
def train_sklearn(model_name: str, X_train: np.ndarray, y_train: np.ndarray,
                  X_test: np.ndarray, y_test: np.ndarray,
                  seed: int = 42, **kwargs) -> Dict[str, Any]:
    from sklearn.preprocessing import StandardScaler
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.linear_model import LogisticRegression
    from sklearn.naive_bayes import GaussianNB
    from sklearn.ensemble import RandomForestClassifier

    scaler = StandardScaler()
    X_tr = scaler.fit_transform(X_train)
    X_te = scaler.transform(X_test)

    if model_name == "KNN":
        clf = KNeighborsClassifier(n_neighbors=kwargs.get("n_neighbors", 5))
    elif model_name == "LogisticRegression":
        clf = LogisticRegression(max_iter=1000,
                                 C=kwargs.get("C", 1.0), random_state=seed)
    elif model_name == "GaussianNB":
        clf = GaussianNB()
    elif model_name == "RandomForest":
        clf = RandomForestClassifier(n_estimators=kwargs.get("n_estimators", 100),
                                     random_state=seed)
    else:
        raise ValueError(f"Unknown sklearn model: {model_name}")

    t0 = time.time()
    clf.fit(X_tr, y_train)
    train_time = time.time() - t0

    y_pred = clf.predict(X_te)
    y_proba = clf.predict_proba(X_te)
    metrics = evaluate_metrics(y_test, y_pred, y_proba)

    return {"model": model_name, "metrics": metrics, "train_time_sec": train_time}


# =============================================
# TFN (PyTorch)
# =============================================
def train_tfn(X_train: np.ndarray, y_train: np.ndarray,
              X_test: np.ndarray, y_test: np.ndarray,
              seed: int = 42, epochs: int = 50, lr: float = 5e-5,
              batch_size: int = 32, fusion: str = "tfn",
              device_str: str = "auto") -> Dict[str, Any]:
    import torch
    import torch.nn as nn
    from torch.utils.data import DataLoader, TensorDataset

    sys.path.insert(0, str(_PROJECT_ROOT / "TFN"))
    from net import ModelConfig, HybridFusionNet

    if device_str == "auto":
        device_str = "cuda" if torch.cuda.is_available() else "cpu"
    device = torch.device(device_str)

    # Standardize
    mu_e = np.nanmean(X_train[:, :16], axis=0)
    sd_e = np.nanstd(X_train[:, :16], axis=0)
    sd_e = np.where(sd_e > 1e-8, sd_e, 1.0)
    mu_h = np.nanmean(X_train[:, 16:], axis=0)
    sd_h = np.nanstd(X_train[:, 16:], axis=0)
    sd_h = np.where(sd_h > 1e-8, sd_h, 1.0)

    def norm(X):
        xe = (X[:, :16] - mu_e) / (sd_e + 1e-8)
        xh = (X[:, 16:] - mu_h) / (sd_h + 1e-8)
        return xe.astype(np.float32), xh.astype(np.float32)

    xe_tr, xh_tr = norm(X_train)
    xe_te, xh_te = norm(X_test)

    ds_train = TensorDataset(torch.from_numpy(xe_tr), torch.from_numpy(xh_tr),
                             torch.from_numpy(y_train.astype(np.int64)))
    ds_test = TensorDataset(torch.from_numpy(xe_te), torch.from_numpy(xh_te),
                            torch.from_numpy(y_test.astype(np.int64)))
    dl_train = DataLoader(ds_train, batch_size=batch_size, shuffle=True)
    dl_test = DataLoader(ds_test, batch_size=batch_size, shuffle=False)

    # Class weights
    counts = np.bincount(y_train, minlength=3)
    w = (counts.sum() / (counts + 1e-6)).astype(np.float32)
    w = w / np.mean(w)
    class_weights = torch.tensor(w, dtype=torch.float32, device=device)

    torch.manual_seed(seed)
    cfg = ModelConfig(eye_feat_dim=16, heart_feat_dim=16, num_classes=3, fusion=fusion)
    model = HybridFusionNet(cfg).to(device)
    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    best_acc = -1.0
    t0 = time.time()

    for epoch in range(1, epochs + 1):
        model.train()
        for xe, xh, y in dl_train:
            xe, xh, y = xe.to(device), xh.to(device), y.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(xe, xh)
            loss = criterion(logits, y)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

        # Evaluate
        model.eval()
        ys, yp, prob = [], [], []
        with torch.no_grad():
            for xe, xh, y in dl_test:
                xe, xh = xe.to(device), xh.to(device)
                logits = model(xe, xh)
                p = torch.softmax(logits, dim=1)
                ys.append(y.numpy())
                yp.append(torch.argmax(p, dim=1).cpu().numpy())
                prob.append(p.cpu().numpy())

        y_true = np.concatenate(ys)
        y_pred = np.concatenate(yp)
        y_proba = np.concatenate(prob)
        metrics = evaluate_metrics(y_true, y_pred, y_proba)

        if metrics["acc"] > best_acc:
            best_acc = metrics["acc"]
            best_metrics = metrics.copy()

        if epoch % 10 == 0 or epoch == epochs:
            print(f"  [TFN] epoch={epoch}/{epochs} acc={metrics['acc']:.4f} "
                  f"f1={metrics['f1_macro']:.4f}")

    train_time = time.time() - t0
    return {"model": f"TFN({fusion})", "metrics": best_metrics, "train_time_sec": train_time,
            "epochs": epochs}


# =============================================
# Main
# =============================================
ALL_MODELS = ["KNN", "LogisticRegression", "GaussianNB", "RandomForest", "TFN"]


def main() -> None:
    ap = argparse.ArgumentParser(description="Train & test all baseline models")
    ap.add_argument("--data_dir", type=str, default="prepared_data",
                    help="Directory with features.npz from prepare_data.py")
    ap.add_argument("--models", nargs="*", default=None,
                    help=f"Models to run (default: all). Choices: {ALL_MODELS}")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--outdir", type=str, default="comparison/results")
    # TFN-specific
    ap.add_argument("--tfn_epochs", type=int, default=50)
    ap.add_argument("--tfn_lr", type=float, default=5e-5)
    ap.add_argument("--tfn_batch_size", type=int, default=32)
    ap.add_argument("--tfn_fusion", type=str, default="tfn", choices=["tfn", "xattn"])
    ap.add_argument("--device", type=str, default="auto")
    args = ap.parse_args()

    data_dir = Path(args.data_dir)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    models = args.models if args.models else ALL_MODELS

    print(f"[info] loading data from {data_dir.resolve()}")
    X, y, is_train, is_test = load_prepared_data(data_dir)
    X_train, y_train = X[is_train], y[is_train]
    X_test, y_test = X[is_test], y[is_test]
    print(f"[info] train: {X_train.shape[0]} windows, test: {X_test.shape[0]} windows")
    print(f"[info] features: {X.shape[1]} dims")
    print(f"[info] models to run: {models}\n")

    results = []
    for model_name in models:
        print(f"{'='*50}")
        print(f"Training: {model_name}")
        print(f"{'='*50}")

        if model_name == "TFN":
            result = train_tfn(
                X_train, y_train, X_test, y_test,
                seed=args.seed, epochs=args.tfn_epochs, lr=args.tfn_lr,
                batch_size=args.tfn_batch_size, fusion=args.tfn_fusion,
                device_str=args.device,
            )
        else:
            result = train_sklearn(model_name, X_train, y_train, X_test, y_test,
                                   seed=args.seed)

        results.append(result)
        m = result["metrics"]
        print(f"  -> acc={m['acc']:.4f}  recall={m['recall_macro']:.4f}  "
              f"f1={m['f1_macro']:.4f}  auc={m['auc_ovr_macro']:.4f}  "
              f"({result['train_time_sec']:.1f}s)\n")

    # Summary table
    print(f"\n{'='*70}")
    print(f"{'Model':<22} {'Acc':>8} {'Recall':>8} {'F1':>8} {'AUC':>8}")
    print(f"{'-'*70}")
    for r in results:
        m = r["metrics"]
        print(f"{r['model']:<22} {m['acc']:>8.4f} {m['recall_macro']:>8.4f} "
              f"{m['f1_macro']:>8.4f} {m['auc_ovr_macro']:>8.4f}")
    print(f"{'='*70}")

    # Save results
    summary = {"models": results, "args": vars(args)}
    out_path = outdir / "comparison_results.json"
    out_path.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n[saved] {out_path.resolve()}")


if __name__ == "__main__":
    main()
